### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by liuzefengi** [lturing/VDO_SLAM_modified#3]
十分感谢您杰出的工作，但是我在复现时编译出错！
[ 94%] Building CXX object CMakeFiles/vdo_slam.dir/example/vdo_slam.cc.o
/home/kong/project/VDO_SLAM_modified-main/example/vdo_slam.cc: In function ‘int main(int, char**)’:
/home/kong/project/VDO_SLAM_modified-main/example/vdo_slam.cc:158:27: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<SegmentedObject>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
         for (int i = 0; i < result[0].size(); ++i)
                         ~~^~~~~~~~~~~~~~~~~~
[100%] Linking CXX executable ../example/vdo_slam
../lib/libObjSLAM.so：对‘OrtSessionOptionsAppendExecutionProvider_CUDA’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/vdo_slam.dir/build.make:190: recipe for target '../example/vdo_slam' failed
make[2]: *** [../example/vdo_slam] Error 1
CMakeFiles/Makefile2:123: recipe for target 'CMakeFiles/vdo_slam.dir/all' failed
make[1]: *** [CMakeFiles/vdo_slam.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2
请问这个错误是什么原因呢

**Comment by lturing** [comment]
删掉[这些行](https://github.com/lturing/VDO_SLAM_modified/blob/main/CMakeLists.txt#L96C1-L105C18)，然后新添加一行，内容为：
ADD_DEFINITIONS( -DCUDA_STATUS=false )
